name: challenge_dev_flutter
description: "Challenge Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  http: ^1.4.0
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
